[package]
name = "fast-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bincode = { version = "2.0.0-rc.3", features = ["derive"] }
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
